[package]
name = "asl-lang"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
parity-wasm = "0.32.0"
lalrpop-util = "0.16.0"
regex = "1.0.5"
specs = "0.12.3"
specs-derive = "0.2.0"

[build-dependencies]
lalrpop = "0.16.0"
